FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN corepack enable
RUN npm install --frozen-lockfile
COPY . .
RUN npm run build

FROM node:22-alpine
ENV NODE_ENV=production
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/build ./build
EXPOSE 3000
CMD ["node", "build"]

