docker-build:
	docker build -t asia-east1-docker.pkg.dev/seo-manager-429705/test-joe-svelte-app/svelte-app:latest --platform linux/amd64 -f Dockerfile .
docker-push:
	docker push asia-east1-docker.pkg.dev/seo-manager-429705/test-joe-svelte-app/svelte-app:latest