apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod
namespace: test-joe # 在這裡指定 namespace

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
